Repository knoxville-utilities-board/nrg-ui, pull requests merged in 2024-11, with the labels that each got.

#244 chore(ci): Run all actions on Node.js 20
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/plan-release.yml
  .github/workflows/publish-unstable.yml
  .github/workflows/publish.yml
Labels: internal

#243 feat: Create datetime component for forms
  apps/docs-app/app/components/f/form/datetime.gts
  apps/docs-app/app/router.ts
  apps/docs-app/app/templates/components.hbs
  apps/docs-app/app/templates/components/form/datetime.hbs
  apps/test-app/package.json
  apps/test-app/tests/integration/components/form/-private/calendar-test.gts
  apps/test-app/tests/integration/components/form/datetime-test.gts
  packages/design-system/src/_forms.scss
  packages/ember-core/.template-lintrc.cjs
  packages/ember-core/package.json
  packages/ember-core/rollup.config.mjs
  packages/ember-core/src/components/form/-private/calendar.gts
  packages/ember-core/src/components/form/bound-value.ts
  packages/ember-core/src/components/form/datetime.gts
  packages/ember-core/src/components/form/field.gts
  packages/ember-core/src/components/index.ts
  packages/ember-core/src/index.ts
  packages/ember-core/src/initializers/dayjs-plugins.ts
  packages/ember-core/src/modifiers/index.ts
  packages/ember-core/src/modifiers/on-click-outside.ts
  packages/ember-core/translations/en-us.json
  pnpm-lock.yaml
Labels: enhancement

#245 feat: Add dark mode support and theme switching
  apps/docs-app/app/components/f/theme-switcher.gts
  apps/docs-app/app/components/theme-page.gts
  apps/docs-app/app/index.html
  apps/docs-app/app/router.ts
  apps/docs-app/app/routes/application.ts
  apps/docs-app/app/templates/components.hbs
  apps/docs-app/app/templates/components/theme-switcher.hbs
  apps/test-app/tests/integration/components/theme-switcher-test.gts
  packages/design-system/src/_bootstrap-config.scss
  packages/ember-core/package.json
  packages/ember-core/src/components/theme-switcher.gts
  packages/ember-core/src/index.ts
  packages/ember-core/src/services/theme.ts
Labels: enhancement

#248 feat(docs): Update code highlighting when theme changes
  apps/docs-app/app/components/code-block.gts
  apps/docs-app/app/controllers/application.ts
  apps/docs-app/app/routes/application.ts
  apps/docs-app/app/services/application.ts
  apps/docs-app/app/services/theme.js
  apps/docs-app/app/templates/application.hbs
  apps/docs-app/app/templates/index.hbs
  packages/ember-core/src/services/theme.ts
Labels: documentation

#247 docs(datetime): Add full documentation
  apps/docs-app/app/components/f/form/datetime.gts
  packages/ember-core/src/components/form/-private/calendar.gts
  packages/ember-core/src/components/form/datetime.gts
  packages/ember-core/translations/en-us.json
Labels: documentation

#250 feat: Improved dark mode support
  apps/docs-app/app/components/code-block.gts
  apps/docs-app/app/components/f/mktg/promo-container.gts
  apps/docs-app/app/services/theme.js
  apps/docs-app/app/styles/app.css
  apps/docs-app/app/styles/freestyle.css
  apps/docs-app/app/styles/marketing-theme.css
  apps/test-app/tests/integration/components/mktg/card-test.gts
  packages/ember-core/src/components/card.gts
  packages/ember-core/src/components/mktg/card.gts
  packages/ember-core/src/components/page-not-found.gts
Labels: enhancement

#251 feat(standards): Install library when migrating
  packages/standards/src/cli/commands/tools/eslint.ts
  packages/standards/src/cli/index.ts
Labels: enhancement

#252 fix(standards): Install multiple dependencies in single command
  packages/standards/src/cli/utils/dependencies.ts
Labels: bug

#254 feat(standards): Use @babel/eslint-parser for JS
  .github/workflows/ci.yml
  .github/workflows/publish-unstable.yml
  .github/workflows/publish.yml
  packages/standards/package.json
  packages/standards/src/index.ts
  packages/standards/src/tools/eslint.ts
Labels: enhancement

#256 chore: Upgrade dependencies
  apps/docs-app/package.json
  apps/test-app/package.json
  package.json
  packages/ember-core/package.json
  pnpm-lock.yaml
Labels: internal

#255 fix(standards): Specify version correctly when installing package
  packages/standards/src/cli/commands/tools/eslint.ts
Labels: bug

#260 chore: Upgrade dependencies
  .github/workflows/ci.yml
  apps/docs-app/package.json
  apps/test-app/package.json
  package.json
  packages/ember-core/package.json
  pnpm-lock.yaml
Labels: internal, dependencies

#262 fix(standards): Check for dependencies when installing many
  packages/standards/src/cli/utils/dependencies.ts
Labels: bug

#264 fix(standards): Configure Babel parser
  packages/standards/src/tools/eslint.ts
Labels: bug

#267 feat: Theme switcher only switches light and dark
  apps/test-app/tests/integration/components/theme-switcher-test.gts
  packages/ember-core/src/components/theme-switcher.gts
  packages/ember-core/src/services/theme.ts
Labels: enhancement

#271 feat(ci): Retain previous configuration if `migrate` is run multiple times
  packages/standards/src/cli/commands/tools/eslint.ts
  packages/standards/src/cli/utils/dependencies.ts
  packages/standards/src/tools/eslint.ts
Labels: enhancement

#278 fix: Add destructor to field component for validations
  apps/docs-app/app/components/f/form/index.gts
  packages/ember-core/src/components/form/field.gts
Labels: bug
