Repository knoxville-utilities-board/nrg-ui, pull requests merged in 2024-10, with the labels that each got.

#168 fix(button): Preserve size with loading state
  apps/docs-app/ember-cli-build.js
  apps/docs-app/package.json
  apps/test-app/tests/integration/components/button-test.gts
  package.json
  packages/design-system/index.js
  packages/design-system/src/_buttons.scss
  packages/ember-core/src/components/button.gts
  pnpm-lock.yaml
Labels: bug

#135 feat: Add modal component
  apps/docs-app/app/components/f/modal.gts
  apps/docs-app/app/router.ts
  apps/docs-app/app/templates/components.hbs
  apps/docs-app/app/templates/components/modal.hbs
  apps/docs-app/tsconfig.json
  apps/test-app/tests/integration/components/modal-test.gts
  apps/test-app/tests/unit/services/modal-test.ts
  apps/test-app/tsconfig.json
  packages/design-system/src/_modal.scss
  packages/design-system/src/main.scss
  packages/ember-core/package.json
  packages/ember-core/src/components/modal.gts
  packages/ember-core/src/index.ts
  packages/ember-core/src/services/modal.ts
Labels: enhancement

#136 feat: Add toast component
  apps/docs-app/app/components/f/toaster.gts
  apps/docs-app/app/router.ts
  apps/docs-app/app/templates/components.hbs
  apps/docs-app/app/templates/components/toaster.hbs
  apps/test-app/tests/integration/components/toaster-test.gts
  packages/design-system/src/_toasts.scss
  packages/design-system/src/main.scss
  packages/ember-core/package.json
  packages/ember-core/src/components/index.ts
  packages/ember-core/src/components/toaster.gts
  packages/ember-core/src/index.ts
  packages/ember-core/src/services/toast.ts
Labels: enhancement

#175 feat: Add spread attributes to toaster
  packages/ember-core/src/components/toaster.gts
Labels: enhancement

#174 fix: Change icon spacing based on type
  packages/ember-core/src/components/mktg/feature-list.gts
Labels: internal

#177 feat: Improved styling for fixed toaster
  apps/docs-app/app/components/f/toaster.gts
  apps/docs-app/app/templates/components.hbs
  packages/design-system/src/_toasts.scss
  packages/ember-core/src/components/toaster.gts
Labels: enhancement

#178 feat: Add margins to form fields
  apps/docs-app/app/components/f/form/index.gts
  packages/design-system/src/_forms.scss
  packages/ember-core/src/components/form/checkbox-group.gts
  packages/ember-core/src/components/form/radio-group.gts
Labels: enhancement

#176 feat: Add styling for placeholder opacity
  packages/design-system/src/_forms.scss
Labels: enhancement

#182 chore(security): Create Dependabot config file
  .github/dependabot.yml
Labels: internal

#189 chore(dependabot): Ignore major version updates
  .github/dependabot.yml
Labels: internal

#191 chore: Update eslint import and fix linting
  apps/docs-app/package.json
  apps/test-app/package.json
  packages/ember-core/package.json
  packages/ember-core/src/validation/types.ts
  pnpm-lock.yaml
Labels: internal

#193 fix(select): Remove validation icon and allow background color
  packages/design-system/src/_forms.scss
Labels: bug

#204 chore: Move styling from workflowtray into library
  packages/ember-core/src/components/mktg/workflow-tray.gts
Labels: enhancement

#205 feat: Add border bottom to marketing header
  packages/ember-core/src/components/mktg/header.gts
Labels: enhancement

#197 chore(ci): Rename `push-dist` workflow to `publish-unstable`
  .github/workflows/publish-unstable.yml
Labels: internal

#209 feat: Update installation blueprint
  packages/ember-core/blueprints/@nrg-ui-core/index.js
  packages/ember-core/package.json
Labels: bug, enhancement

#210 feat: Update and extract phone formatter
  apps/test-app/tests/unit/utils/phone-test.ts
  packages/ember-core/package.json
  packages/ember-core/rollup.config.mjs
  packages/ember-core/src/components/form/phone-input.gts
  packages/ember-core/src/utils/phone.ts
Labels: enhancement

#213 feat(text-input): Allow custom formatting
  apps/test-app/tests/integration/components/form/text-input-test.gts
  packages/ember-core/src/components/form/text-input.gts
Labels: enhancement

#212 refactor: Remove extraneous padding on cards
  apps/test-app/tests/integration/components/card-test.gts
  apps/test-app/tests/integration/components/mktg/card-container-test.gts
  packages/ember-core/src/components/card.gts
  packages/ember-core/src/components/mktg/card-container.gts
Labels: internal

#194 feat: Add theme page
  apps/docs-app/app/components/theme-page.gts
  apps/docs-app/app/router.ts
  apps/docs-app/app/styles/marketing-theme.css
  apps/docs-app/app/templates/index.hbs
  apps/docs-app/app/templates/theme.hbs
  apps/test-app/app/styles/marketing-theme.css
Labels: documentation

#218 feat(form): Scroll to first invalid field by default
  packages/ember-core/package.json
  packages/ember-core/src/components/form/index.gts
  packages/ember-core/src/utils/dom.ts
Labels: enhancement

#220 feat(dependabot): Ignore minor Ember.js versions
  .github/dependabot.yml
Labels: internal

#225 feat: Create new package for enforceable standards
  package.json
  packages/ember-core/.eslintignore
  packages/ember-core/.eslintrc.cjs
  packages/ember-core/addon-main.cjs
  packages/ember-core/eslint.config.mjs
  packages/ember-core/package.json
  packages/ember-core/src/components/button-group.gts
  packages/ember-core/src/components/button.gts
  packages/ember-core/src/components/card.gts
  packages/ember-core/src/components/form/index.gts
  packages/ember-core/src/components/icon.gts
  packages/ember-core/src/components/mktg/faq.gts
  packages/ember-core/src/services/toast.ts
  packages/ember-core/src/validation/utils.ts
  packages/ember-core/unpublished-development-types/index.d.ts
  packages/standards/.gitignore
  packages/standards/README.md
  packages/standards/eslint.config.mjs
  packages/standards/package.json
  packages/standards/src/index.ts
  packages/standards/src/logging.ts
  packages/standards/src/tools/eslint.ts
  packages/standards/src/utils.ts
  packages/standards/tsconfig.json
  packages/standards/types/index.d.ts
  pnpm-lock.yaml
Labels: enhancement, internal

#226 feat(docs-app): Use new standards library
  apps/docs-app/.eslintignore
  apps/docs-app/.eslintrc.js
  apps/docs-app/app/components/f/form/index.gts
  apps/docs-app/config/ember-try.js
  apps/docs-app/ember-cli-build.js
  apps/docs-app/eslint.config.mjs
  apps/docs-app/package.json
  package.json
  packages/standards/README.md
  packages/standards/package.json
  packages/standards/src/tools/eslint.ts
  packages/standards/types/index.d.ts
  pnpm-lock.yaml
Labels: enhancement, internal

#231 feat: Require named imports be alphabetical
  apps/docs-app/app/components/f/form/checkbox-group.gts
  apps/docs-app/app/components/f/form/checkbox.gts
  apps/docs-app/app/components/f/form/index.gts
  apps/docs-app/app/components/f/form/phone-input.gts
  apps/docs-app/app/components/f/form/radio-group.gts
  apps/docs-app/app/components/f/form/select.gts
  apps/docs-app/app/components/f/form/text-area.gts
  apps/docs-app/app/components/f/form/text-input.gts
  apps/docs-app/app/components/f/modal.gts
  apps/docs-app/app/components/theme-page.gts
  apps/docs-app/config/ember-try.js
  apps/docs-app/tests/helpers/index.ts
  packages/ember-core/src/components/form/index.gts
  packages/ember-core/src/components/form/select.gts
  packages/ember-core/src/index.ts
  packages/ember-core/src/services/toast.ts
  packages/standards/src/tools/eslint.ts
Labels: enhancement

#234 feat: Add theme generator cli
  packages/theme-generator/README.md
  packages/theme-generator/bin/nrg-theme-generator.js
  packages/theme-generator/package.json
  packages/theme-generator/src/cleanup.js
  packages/theme-generator/src/compile-css.js
  packages/theme-generator/src/custom-variables.scss
  packages/theme-generator/src/extract-theme.js
  packages/theme-generator/src/extract-variables.js
  packages/theme-generator/src/index.js
  packages/theme-generator/src/install-nrg-css.js
  packages/theme-generator/src/prettify.js
  packages/theme-generator/src/split-theme.js
  packages/theme-generator/src/theme.scss
  packages/theme-generator/src/variable-compression.js
  pnpm-lock.yaml
Labels: enhancement

#240 chore(ci): Remove extraneous workflow inputs
  .github/workflows/plan-release.yml
Labels: internal

#241 feat(theme-generator): Generate diff from base css
  packages/design-system/src/_color-variants.scss
  packages/design-system/src/main.scss
  packages/theme-generator/package.json
  packages/theme-generator/src/cleanup.js
  packages/theme-generator/src/compile-css.js
  packages/theme-generator/src/dependencies.js
  packages/theme-generator/src/extract-variables.js
  packages/theme-generator/src/index.js
  packages/theme-generator/src/install-nrg-css.js
  packages/theme-generator/src/read-themes.js
  packages/theme-generator/src/split-theme.js
  packages/theme-generator/src/tree-diff.js
  packages/theme-generator/src/variable-compression.js
  pnpm-lock.yaml
Labels: enhancement
