Repository knoxville-utilities-board/nrg-ui, pull requests merged in 2024-08, with the labels that each got.

#82 chore: Require labels for PRs
  .github/workflows/require-labels.yml
Labels: internal

#81 auto-chore: Format repository
  apps/ember-test-app/app/index.html
  apps/ember-test-app/app/templates/application.hbs
  apps/ember-test-app/app/templates/components/header.hbs
  apps/ember-test-app/app/templates/index.hbs
  apps/ember-test-app/app/templates/marketing.hbs
  apps/ember-test-app/tests/index.html
  packages/theme-generator/.prettierignore
  packages/theme-generator/README.md
  packages/theme-generator/package.json
Labels: internal

#83 chore: Update text for required labels comment
  .github/workflows/require-labels.yml
Labels: internal

#84 feat(ci): Push dist for addon and CSS to GH
  .github/workflows/push-dist.yml
Labels: internal

#86 chore: Pack dist folder of design system
  packages/design-system/package.json
Labels: internal

#88 fix: Include blueprints in published package
  packages/ember/package.json
Labels: internal

#89 chore: Add CODEOWNERS
  .github/CODEOWNERS
Labels: internal

#87 docs: Implement freestyle docs for footer
  apps/ember-test-app/app/components/f/footer.gts
  apps/ember-test-app/app/router.ts
  apps/ember-test-app/app/templates/components.hbs
  apps/ember-test-app/app/templates/components/footer.hbs
Labels: documentation

#85 feat(ci): Use release-plan for managing and publishing releases
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  .github/workflows/push-dist.yml
  CHANGELOG.md
  RELEASE.md
  apps/ember-test-app/package.json
  package.json
  pnpm-lock.yaml
Labels: enhancement, internal

#91 chore(ci): Use conventional commit message for release PR
  .github/release-commit-message.js
  .github/workflows/plan-release.yml
Labels: internal

#92 chore: Tweak description of release pull request
  .github/workflows/plan-release.yml
Labels: internal

#93 chore(ember): Add @nrg-ui/css to devDependencies
  packages/ember/package.json
  pnpm-lock.yaml
Labels: internal

#94 chore: Improve generation of release commit message
  .github/release-commit-message.js
  packages/theme-generator/package.json
Labels: internal

#95 chore: Appease Sonarlint
  .github/release-commit-message.js
Labels: internal

#96 chore(ember): Limit semver range for CSS library
  packages/ember/package.json
  pnpm-lock.yaml
Labels: internal

#98 feat(blueprint): Install CSS library when addon is installed
  packages/ember/blueprints/@nrg-ui-ember/index.js
Labels: enhancement

#108 chore: Move form component routes under "Components"
  apps/ember-test-app/app/components/f/form/index.gts
  apps/ember-test-app/app/components/f/form/phone-field.gts
  apps/ember-test-app/app/components/f/form/radio-group.gts
  apps/ember-test-app/app/components/f/form/text-area.gts
  apps/ember-test-app/app/components/f/form/text-field.gts
  apps/ember-test-app/app/router.ts
  apps/ember-test-app/app/templates/components.hbs
  apps/ember-test-app/app/templates/components/form/index.hbs
  apps/ember-test-app/app/templates/components/form/phone-field.hbs
  apps/ember-test-app/app/templates/components/form/radio-group.hbs
  apps/ember-test-app/app/templates/components/form/select.hbs
  apps/ember-test-app/app/templates/components/form/text-area.hbs
  apps/ember-test-app/app/templates/components/form/text-field.hbs
Labels: internal

#111 chore: Use bot account to open release PR
  .github/workflows/plan-release.yml
Labels: internal

#109 chore: Enable no-bare-strings for improved i18n
  apps/ember-test-app/tests/helpers/index.ts
  apps/ember-test-app/tests/integration/components/alert-test.gts
  apps/ember-test-app/tests/integration/components/button-group-test.gts
  apps/ember-test-app/tests/integration/components/button-test.gts
  apps/ember-test-app/tests/integration/components/card-test.gts
  apps/ember-test-app/tests/integration/components/footer-test.gts
  apps/ember-test-app/tests/integration/components/form/checkbox-test.gts
  apps/ember-test-app/tests/integration/components/form/index-test.gts
  apps/ember-test-app/tests/integration/components/form/phone-field-test.gts
  apps/ember-test-app/tests/integration/components/form/radio-group-test.gts
  apps/ember-test-app/tests/integration/components/form/select-test.gts
  apps/ember-test-app/tests/integration/components/form/text-area-test.gts
  apps/ember-test-app/tests/integration/components/form/text-field-test.gts
  apps/ember-test-app/tests/integration/components/header-test.gts
  apps/ember-test-app/tests/integration/components/icon-test.gts
  apps/ember-test-app/tests/integration/components/loading-indicator-test.gts
  apps/ember-test-app/tests/integration/components/mktg/card-container-test.gts
  apps/ember-test-app/tests/integration/components/mktg/card-test.gts
  apps/ember-test-app/tests/integration/components/mktg/faq-test.gts
  apps/ember-test-app/tests/integration/components/mktg/feature-list-test.gts
  apps/ember-test-app/tests/integration/components/mktg/footer-test.gts
  apps/ember-test-app/tests/integration/components/mktg/header-test.gts
  apps/ember-test-app/tests/integration/components/mktg/navbar-test.gts
  apps/ember-test-app/tests/integration/components/mktg/promo-container-test.gts
  apps/ember-test-app/tests/integration/components/mktg/promo-test.gts
  apps/ember-test-app/tests/integration/components/mktg/section-header-test.gts
  apps/ember-test-app/tests/integration/components/mktg/service-pricing-test.gts
  apps/ember-test-app/tests/integration/components/mktg/workflow-tray-test.gts
  apps/ember-test-app/tests/integration/components/progress-test.gts
  packages/ember/.template-lintrc.cjs
  packages/ember/src/components/alert.gts
  packages/ember/src/components/button.gts
  packages/ember/src/components/form/select.gts
  packages/ember/src/components/mktg/navbar.gts
  packages/ember/translations/en-us.json
Labels: internal

#113 fix: Ensure checkbox label is always clickable
  packages/design-system/src/_forms.scss
  packages/ember/src/components/form/checkbox.gts
Labels: bug

#115 chore(ci): Open release plan PR in draft
  .github/workflows/plan-release.yml
Labels: internal

#117 feat(confirmation): Add `inverse` option
  apps/ember-test-app/tests/unit/validators/confirmation-test.ts
  packages/ember/src/validation/validators/confirmation.ts
  packages/ember/translations/en-us.json
Labels: enhancement

#118 feat: Add phone validator
  apps/ember-test-app/tests/unit/validators/phone-test.ts
  packages/ember/src/components/form/phone-field.gts
  packages/ember/src/utils/phone-formats.ts
  packages/ember/src/utils/phone.ts
  packages/ember/src/validation/index.ts
  packages/ember/src/validation/utils.ts
  packages/ember/src/validation/validators/phone.ts
  packages/ember/translations/en-us.json
Labels: enhancement

#127 feat: Add email validator
  apps/ember-test-app/tests/unit/validators/email-test.ts
  packages/ember/src/utils/email.ts
  packages/ember/src/validation/index.ts
  packages/ember/src/validation/utils.ts
  packages/ember/src/validation/validators/email.ts
  packages/ember/translations/en-us.json
Labels: enhancement

#128 chore(tests): Add helpers for testing validations
  apps/ember-test-app/tests/helpers/index.ts
  apps/ember-test-app/tests/unit/validators/base-test.ts
  apps/ember-test-app/tests/unit/validators/confirmation-test.ts
  apps/ember-test-app/tests/unit/validators/custom-test.ts
  apps/ember-test-app/tests/unit/validators/email-test.ts
  apps/ember-test-app/tests/unit/validators/exclusion-test.ts
  apps/ember-test-app/tests/unit/validators/inclusion-test.ts
  apps/ember-test-app/tests/unit/validators/length-test.ts
  apps/ember-test-app/tests/unit/validators/number-test.ts
  apps/ember-test-app/tests/unit/validators/phone-test.ts
  apps/ember-test-app/tests/unit/validators/presence-test.ts
  apps/ember-test-app/tests/unit/validators/range-test.ts
  apps/ember-test-app/tests/unit/validators/regex-test.ts
Labels: internal

#129 refactor: Rename -Field components to -Input
  apps/ember-test-app/app/components/f/form/index.gts
  apps/ember-test-app/app/components/f/form/phone-input.gts
  apps/ember-test-app/app/components/f/form/text-input.gts
  apps/ember-test-app/app/router.ts
  apps/ember-test-app/app/templates/components.hbs
  apps/ember-test-app/app/templates/components/form/phone-field.hbs
  apps/ember-test-app/app/templates/components/form/phone-input.hbs
  apps/ember-test-app/app/templates/components/form/text-field.hbs
  apps/ember-test-app/app/templates/components/form/text-input.hbs
  apps/ember-test-app/tests/integration/components/form/index-test.gts
  apps/ember-test-app/tests/integration/components/form/number-input-test.gts
  apps/ember-test-app/tests/integration/components/form/phone-input-test.gts
  apps/ember-test-app/tests/integration/components/form/text-input-test.gts
  packages/ember/package.json
  packages/ember/src/components/form/field.gts
  packages/ember/src/components/form/number-input.gts
  packages/ember/src/components/form/phone-input.gts
  packages/ember/src/components/form/radio-group.gts
  packages/ember/src/components/form/text-input.gts
Labels: internal

#119 docs: Implement freestyle docs for service pricing
  apps/ember-test-app/app/components/f/mktg/service-pricing.gts
  apps/ember-test-app/app/router.ts
  apps/ember-test-app/app/templates/mktg-components.hbs
  apps/ember-test-app/app/templates/mktg-components/service-pricing.hbs
Labels: documentation

#131 refactor(phone): Format on blur instead of on type
  apps/ember-test-app/tests/integration/components/form/phone-input-test.gts
  packages/ember-core/src/components/form/phone-input.gts
  packages/ember-core/src/utils/phone.ts
Labels: enhancement

#132 chore(ci): Update directory name
  .github/workflows/push-dist.yml
Labels: internal
