Repository knoxville-utilities-board/nrg-ui, pull requests merged in 2024-09, with the labels that each got.

#134 feat: Add dropSection param to prevent excess padding when not present
  apps/ember-test-app/app/components/f/mktg/header.gts
  apps/ember-test-app/tests/integration/components/header-test.gts
  apps/ember-test-app/tests/integration/components/mktg/header-test.gts
  packages/ember-core/src/components/header.gts
  packages/ember-core/src/components/mktg/header.gts
Labels: enhancement

#137 feat: Add repository to package.json files
  packages/design-system/package.json
  packages/ember-core/package.json
Labels: internal

#120 docs: Implement freestyle docs for marketing footer
  apps/ember-test-app/app/components/f/mktg/footer.gts
  apps/ember-test-app/app/router.ts
  apps/ember-test-app/app/templates/mktg-components.hbs
  apps/ember-test-app/app/templates/mktg-components/footer.hbs
Labels: documentation

#139 chore(design-system): Don't ship with CSS source maps
  packages/design-system/package.json
Labels: internal

#141 chore: Add link to test page
  apps/test-app/app/templates/application.hbs
Labels: internal

#142 chore: Update rootURL for docs app
  apps/docs-app/config/environment.js
Labels: documentation, internal

#144 refactor: Update service pricing component parameter name
  apps/docs-app/app/components/f/mktg/service-pricing.gts
  apps/test-app/tests/integration/components/mktg/service-pricing-test.gts
  packages/ember-core/src/components/mktg/service-pricing.gts
Labels: internal

#148 feat(css): Enable negative margins
  packages/design-system/src/_bootstrap-config.scss
Labels: enhancement

#149 style(header): Remove padding from header container
  packages/ember-core/src/components/header.gts
Labels: internal

#151 refactor: Remove primary blue background from headers
  apps/docs-app/app/components/f/header.gts
  apps/docs-app/app/components/f/mktg/header.gts
  apps/test-app/tests/integration/components/mktg/faq-test.gts
  packages/ember-core/src/components/header.gts
  packages/ember-core/src/components/mktg/faq.gts
Labels: enhancement

#153 chore: Remove extra div from headers
  packages/ember-core/src/components/header.gts
Labels: internal

#155 feat: Add additional color variants for buttons
  packages/design-system/src/_buttons.scss
  packages/design-system/src/main.scss
Labels: enhancement

#156 fix: Remove default styling wherever it could be overriden
  packages/ember-core/src/components/footer.gts
  packages/ember-core/src/components/icon.gts
  packages/ember-core/src/components/mktg/footer.gts
  packages/ember-core/src/components/mktg/navbar.gts
  packages/ember-core/src/components/mktg/workflow-tray.gts
Labels: bug

#162 fix(responsive): Pass `owner` to superclass constructor
  packages/ember-core/src/services/responsive.ts
Labels: bug

#164 feat: Add exports for all modules at index
  packages/ember-core/package.json
  packages/ember-core/src/components/alert.gts
  packages/ember-core/src/components/button.gts
  packages/ember-core/src/components/footer.gts
  packages/ember-core/src/components/form/index.gts
  packages/ember-core/src/components/header.gts
  packages/ember-core/src/components/icon.gts
  packages/ember-core/src/components/index.ts
  packages/ember-core/src/components/loading-indicator.gts
  packages/ember-core/src/components/mktg/card-container.gts
  packages/ember-core/src/components/mktg/faq.gts
  packages/ember-core/src/components/mktg/feature-list.gts
  packages/ember-core/src/components/mktg/footer.gts
  packages/ember-core/src/components/mktg/header.gts
  packages/ember-core/src/components/mktg/navbar.gts
  packages/ember-core/src/components/mktg/promo-container.gts
  packages/ember-core/src/components/mktg/promo.gts
  packages/ember-core/src/components/mktg/section-header.gts
  packages/ember-core/src/components/mktg/service-pricing.gts
  packages/ember-core/src/components/mktg/workflow-tray.gts
  packages/ember-core/src/components/nav-item.gts
  packages/ember-core/src/components/progress.gts
  packages/ember-core/src/helpers/index.ts
  packages/ember-core/src/index.ts
  packages/ember-core/src/modifiers/index.ts
Labels: enhancement

#165 refactor(presence): Set ignoreBlank option default to true
  apps/test-app/tests/unit/validators/presence-test.ts
  packages/ember-core/src/validation/validators/presence.ts
Labels: internal
