Repository knoxville-utilities-board/nrg-ui, pull requests merged in 2024-12, with the labels that each got.

#286 refactor: Rename `didInsert` modifier to `onInsert`
  apps/docs-app/app/components/code-block.gts
  packages/ember-core/package.json
  packages/ember-core/src/components/form/index.gts
  packages/ember-core/src/components/form/select.gts
  packages/ember-core/src/components/modal.gts
  packages/ember-core/src/index.ts
  packages/ember-core/src/modifiers/index.ts
  packages/ember-core/src/modifiers/on-insert.ts
  packages/ember-core/src/template-registry.ts
Labels: enhancement

#292 chore: Bump required version of ESLint
  packages/standards/src/cli/commands/tools/eslint.ts
Labels: bug

#289 chore: Update Gember config and commands
  package.json
  packages/ember-core/gember.config.mjs
Labels: internal

#294 fix(standards): Add Ember.js ruleset
  packages/standards/src/cli/commands/tools/eslint.ts
Labels: bug

#295 refactor: Update confirmation validator
  apps/docs-app/app/components/f/form/index.gts
  packages/ember-core/src/validation/validators/confirmation.ts
Labels: bug

#297 chore(test-app): Enable full Glint support
  apps/test-app/.eslintignore
  apps/test-app/.eslintrc.js
  apps/test-app/config/ember-try.js
  apps/test-app/ember-cli-build.js
  apps/test-app/eslint.config.mjs
  apps/test-app/package.json
  apps/test-app/tests/helpers/index.ts
  apps/test-app/tests/integration/components/alert-test.gts
  apps/test-app/tests/integration/components/button-group-test.gts
  apps/test-app/tests/integration/components/button-test.gts
  apps/test-app/tests/integration/components/form/-private/calendar-test.gts
  apps/test-app/tests/integration/components/form/checkbox-group-test.gts
  apps/test-app/tests/integration/components/form/checkbox-test.gts
  apps/test-app/tests/integration/components/form/datetime-test.gts
  apps/test-app/tests/integration/components/form/index-test.gts
  apps/test-app/tests/integration/components/form/number-input-test.gts
  apps/test-app/tests/integration/components/form/phone-input-test.gts
  apps/test-app/tests/integration/components/form/radio-group-test.gts
  apps/test-app/tests/integration/components/form/select-test.gts
  apps/test-app/tests/integration/components/form/text-area-test.gts
  apps/test-app/tests/integration/components/form/text-input-test.gts
  apps/test-app/tests/integration/components/mktg/promo-test.gts
  apps/test-app/tests/integration/components/progress-test.gts
  apps/test-app/tests/integration/components/theme-switcher-test.gts
  apps/test-app/tests/unit/utils/phone-test.ts
  apps/test-app/tests/unit/validators/confirmation-test.ts
  apps/test-app/tests/unit/validators/custom-test.ts
  apps/test-app/tests/unit/validators/email-test.ts
  apps/test-app/tests/unit/validators/exclusion-test.ts
  apps/test-app/tests/unit/validators/inclusion-test.ts
  apps/test-app/tests/unit/validators/length-test.ts
  apps/test-app/tests/unit/validators/number-test.ts
  apps/test-app/tests/unit/validators/phone-test.ts
  apps/test-app/tests/unit/validators/presence-test.ts
  apps/test-app/tests/unit/validators/range-test.ts
  apps/test-app/tests/unit/validators/regex-test.ts
  apps/test-app/tsconfig.json
  apps/test-app/types/global.d.ts
  package.json
  packages/ember-core/src/components/form/-private/calendar.gts
  packages/ember-core/src/index.ts
  packages/ember-core/src/services/modal.ts
  packages/ember-core/src/services/theme.ts
  packages/ember-core/src/services/toast.ts
  pnpm-lock.yaml
Labels: internal

#300 feat(standards): Update `eslint-plugin-decorator-position`
  packages/standards/README.md
  packages/standards/src/cli/utils/dependencies.ts
Labels: enhancement

#301 chore: Update `eslint-plugin-decorator-position`
  apps/docs-app/package.json
  apps/test-app/package.json
  packages/ember-core/package.json
  packages/standards/package.json
  pnpm-lock.yaml
Labels: internal

#302 chore: Update READMEs for packages
  README.md
  packages/design-system/README.md
  packages/standards/README.md
Labels: documentation

#303 fix(toasts): Allow clicking behind toaster
  packages/design-system/src/_toasts.scss
Labels: bug

#304 feat: Add `onDestroy` modifier
  apps/test-app/tests/integration/modifiers/on-destroy-test.gts
  packages/ember-core/package.json
  packages/ember-core/src/index.ts
  packages/ember-core/src/modifiers/index.ts
  packages/ember-core/src/modifiers/on-destroy.ts
Labels: enhancement

#306 docs: Add pages for modifiers
  apps/docs-app/app/components/f/modifiers/on-click-outside.gts
  apps/docs-app/app/components/f/modifiers/on-destroy.gts
  apps/docs-app/app/components/f/modifiers/on-insert.gts
  apps/docs-app/app/components/f/modifiers/on-update.gts
  apps/docs-app/app/router.ts
  apps/docs-app/app/styles/app.css
  apps/docs-app/app/templates/modifiers.hbs
  apps/docs-app/app/templates/modifiers/on-click-outside.hbs
  apps/docs-app/app/templates/modifiers/on-destroy.hbs
  apps/docs-app/app/templates/modifiers/on-insert.hbs
  apps/docs-app/app/templates/modifiers/on-update.hbs
Labels: documentation

#290 feat: Add search bar component
  apps/docs-app/app/components/f/form/search.gts
  apps/docs-app/app/router.ts
  apps/docs-app/app/templates/components.hbs
  apps/docs-app/app/templates/components/form/search.hbs
  apps/test-app/tests/integration/components/form/search-test.gts
  packages/design-system/src/_forms.scss
  packages/ember-core/package.json
  packages/ember-core/src/components/form/field.gts
  packages/ember-core/src/components/form/search.gts
  packages/ember-core/src/components/index.ts
  packages/ember-core/src/index.ts
  packages/ember-core/src/template-registry.ts
  packages/ember-core/translations/en-us.json
Labels: enhancement

#311 chore(ci): Enable auto-merge on release-plan PR
  .github/workflows/plan-release.yml
Labels: internal

#313 fix(ci): Fix auto-merge enabling
  .github/workflows/plan-release.yml
Labels: internal

#315 feat: Create popover component
  apps/docs-app/app/components/f/components/popover.gts
  apps/docs-app/app/router.ts
  apps/docs-app/app/styles/app.css
  apps/docs-app/app/templates/components.hbs
  apps/docs-app/app/templates/components/popover.hbs
  apps/test-app/tests/integration/components/popover-test.gts
  packages/design-system/src/_bootstrap.scss
  packages/design-system/src/_popover.scss
  packages/design-system/src/main.scss
  packages/ember-core/package.json
  packages/ember-core/src/components/index.ts
  packages/ember-core/src/components/popover.gts
  packages/ember-core/src/index.ts
  packages/ember-core/src/modifiers/classes.ts
  packages/ember-core/src/modifiers/index.ts
  packages/ember-core/src/utils/dom.ts
  pnpm-lock.yaml
Labels: enhancement

#317 feat: Create tooltip component
  apps/docs-app/app/components/f/components/popover.gts
  apps/docs-app/app/components/f/components/tooltip.gts
  apps/docs-app/app/router.ts
  apps/docs-app/app/templates/components.hbs
  apps/docs-app/app/templates/components/tooltip.hbs
  apps/test-app/tests/integration/components/tooltip-test.gts
  packages/design-system/src/_bootstrap.scss
  packages/ember-core/package.json
  packages/ember-core/src/components/index.ts
  packages/ember-core/src/components/popover.gts
  packages/ember-core/src/components/tooltip.gts
  packages/ember-core/src/helpers/classes.ts
  packages/ember-core/src/helpers/index.ts
  packages/ember-core/src/index.ts
  packages/ember-core/src/modifiers/classes.ts
  packages/ember-core/src/modifiers/index.ts
Labels: enhancement

#319 chore(ci): Don't auto-merge release PRs
  .github/workflows/plan-release.yml
Labels: internal

#320 feat: Create pagination component
  .github/workflows/ci.yml
  apps/docs-app/app/components/f/components/pagination.gts
  apps/docs-app/app/router.ts
  apps/docs-app/app/routes/application.ts
  apps/docs-app/app/templates/components.hbs
  apps/docs-app/app/templates/components/pagination.hbs
  apps/test-app/config/ember-try.js
  apps/test-app/tests/integration/components/pagination-test.gts
  packages/design-system/src/custom/_buttons.scss
  packages/design-system/src/custom/_forms.scss
  packages/design-system/src/custom/_icons.scss
  packages/design-system/src/custom/_modal.scss
  packages/design-system/src/custom/_pagination.scss
  packages/design-system/src/custom/_popover.scss
  packages/design-system/src/custom/_text.scss
  packages/design-system/src/custom/_toasts.scss
  packages/design-system/src/main.scss
  packages/ember-core/package.json
  packages/ember-core/src/components/form/select.gts
  packages/ember-core/src/components/index.ts
  packages/ember-core/src/components/pagination.gts
  packages/ember-core/src/index.ts
  packages/ember-core/translations/en-us.json
  pnpm-lock.yaml
Labels: enhancement
