Repository knoxville-utilities-board/nrg-ui, pull requests merged in 2025-09, with the labels that each got.

#584 feat(datetime): Expose onShow and onHide arguments
  docs/app/components/f/components/form/datetime.gts
  packages/ember-core/src/components/form/datetime.gts
Labels: enhancement

#587 fix(standards): Specify tsconfigRootDir parser option
  packages/standards/src/tools/eslint.ts
Labels: bug

#601 fix(standards): Qunit plugin and template tags with migration
  packages/standards/src/cli/commands/tools/eslint.ts
  packages/standards/src/cli/utils/dependencies.ts
Labels: bug

#604 fix(ci): Publish all packages as public
  packages/app-version/package.json
  packages/code-snippets/package.json
  packages/design-system/package.json
  packages/ember-core/package.json
  packages/standards/package.json
  packages/theme-generator/package.json
Labels: internal

#608 fix(field): Use correct ID for feedback
  packages/ember-core/src/components/form/field.gts
Labels: bug

#610 chore(dependabot): Run on Sunday to spread run load
  .github/dependabot.yml
Labels: internal

#620 feat(dropdown): Add params for icon-only and custom icon dropdowns
  docs/app/components/f/components/dropdown.gts
  packages/ember-core/src/components/dropdown.gts
Labels: enhancement
