Repository knoxville-utilities-board/nrg-ui, pull requests merged in 2025-07, with the labels that each got.

#496 feat: Import media service from ember-responsive
  docs/package.json
  docs/tests/integration/components/scaffold-test.gts
  docs/types/ember-responsive.d.ts
  packages/ember-core/blueprints/@nrg-ui-core/index.js
  packages/ember-core/package.json
  packages/ember-core/src/services/media.ts
  packages/ember-core/src/services/responsive.ts
  packages/ember-core/src/test-support/index.ts
  packages/ember-core/unpublished-development-types/index.d.ts
  pnpm-lock.yaml
Labels: enhancement, breaking

#517 chore(dependabot): Ignore additional packages
  .github/dependabot.yml
Labels: internal

#527 docs: Add code blocks to side-by-side and stacked-pane
  docs/app/templates/side-by-side.hbs
  docs/app/templates/stacked-pane.hbs
Labels: documentation

#529 fix(checkbox-group): Pass correct options to checkbox
  packages/ember-core/src/components/form/checkbox-group.gts
Labels: bug

#530 fix(datetime): Adjust z-index to not show borders
  docs/app/components/f/components/form/index.gts
  packages/design-system/src/custom/_forms.scss
  packages/ember-core/src/components/form/-private/calendar.gts
Labels: bug

#526 chore: Format repository
  packages/ember-core/src/components/form/file-upload.gts
  packages/ember-core/src/components/scaffold.gts
  packages/ember-core/src/components/sidebar.gts
Labels: internal

#532 fix(alert): Add splattributes
  packages/ember-core/src/components/alert.gts
Labels: bug

#535 chore(datetime): Coerce default values to Dates
  packages/ember-core/src/components/form/bound-value.ts
  packages/ember-core/src/components/form/datetime.gts
Labels: bug

#537 fix(form-control): Pass correct field options
  packages/ember-core/src/components/form/datetime.gts
  packages/ember-core/src/components/form/multi-select.gts
  packages/ember-core/src/components/form/search.gts
Labels: bug

#538 chore: Override form-data to patched version
  package.json
  pnpm-lock.yaml
Labels: internal, dependencies

#531 feat(stacked-pane): Add pagination usage example
  docs/app/components/f/components/pagination.gts
  docs/app/controllers/stacked-pane.ts
  docs/app/templates/stacked-pane.hbs
  packages/design-system/src/custom/_stacked-pane.scss
  packages/ember-core/src/components/pagination.gts
  packages/ember-core/src/template-registry.ts
Labels: enhancement

#542 fix(theme-generator): Resolve Prettier promise
  packages/theme-generator/src/index.js
Labels: bug

#553 feat(form): Allow custom submit button class
  packages/ember-core/src/components/form/index.gts
Labels: enhancement
