Repository knoxville-utilities-board/nrg-ui, pull requests merged in 2025-02, with the labels that each got.

#347 fix(standards): Remove leading slashes from ignored files
  packages/standards/src/cli/commands/tools/eslint.ts
Labels: bug

#353 fix(modal): Correct styling and focus when dismissible
  packages/design-system/src/custom/_modal.scss
Labels: bug

#359 fix(search): Modify display value for objects
  packages/ember-core/src/components/form/search.gts
Labels: bug

#358 fix(select,search): Show validation messages
  packages/design-system/src/custom/_forms.scss
  packages/ember-core/src/components/form/search.gts
Labels: bug

#363 fix(popover): Show active option on mobile
  packages/design-system/src/custom/_forms.scss
  packages/ember-core/src/components/popover.gts
Labels: bug

#364 feat(design-system): Export styles and assets
  docs/app/app.ts
  docs/app/assets/css/app.css
  docs/app/assets/css/freestyle.css
  docs/app/assets/css/marketing-theme.css
  docs/ember-cli-build.js
  packages/design-system/package.json
  packages/design-system/src/custom/_icons.scss
Labels: enhancement

#365 feat: Allow configuration of theme generator
  packages/theme-generator/src/config.js
  packages/theme-generator/src/dependencies.js
  packages/theme-generator/src/index.js
Labels: enhancement

#367 chore: Update package contents
  docs/package.json
  packages/app-version/package.json
  packages/design-system/package.json
  packages/ember-core/package.json
  packages/standards/package.json
  packages/theme-generator/package.json
Labels: internal
