Repository knoxville-utilities-board/nrg-ui, pull requests merged in 2025-03, with the labels that each got.

#374 fix(popover): Prevent horizontal scrolling on popover
  packages/design-system/src/custom/_forms.scss
  packages/ember-core/src/components/form/search.gts
  packages/ember-core/src/components/popover.gts
Labels: bug

#372 feat: Update blueprint to use Webpack for CSS
  docs/config/ember-cli-update.json
  docs/package.json
  docs/tests/helpers/index.ts
  packages/ember-core/README.md
  packages/ember-core/blueprints/@nrg-ui-core/files/__app__/app.ts
  packages/ember-core/blueprints/@nrg-ui-core/files/__root__/ember-cli-build.js
  packages/ember-core/blueprints/@nrg-ui-core/index.js
  packages/ember-core/eslint.config.mjs
  packages/ember-core/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: enhancement

#379 chore: Reorganize exports to resolve Webpack warnings
  packages/ember-core/src/components/index.ts
  packages/ember-core/src/helpers/index.ts
  packages/ember-core/src/modifiers/index.ts
  packages/ember-core/src/utils/dom.ts
  packages/ember-core/src/utils/email.ts
  packages/ember-core/src/utils/ensure-path-exists.ts
  packages/ember-core/src/utils/index.ts
  packages/ember-core/src/utils/string.ts
Labels: internal

#378 chore(blueprint): Install @embroider/macros on install
  packages/ember-core/blueprints/@nrg-ui-core/index.js
Labels: bug

#373 fix(search): Prevent displayValue from being set
  packages/ember-core/src/components/form/search.gts
Labels: bug

#384 style(forms): Don't apply top margin to first inputs
  packages/design-system/src/custom/_forms.scss
Labels: bug

#385 feat: Add sidebar component and add default scrollbar styling
  docs/.template-lintrc.js
  docs/app/components/sidebar.gts
  docs/app/templates/application.hbs
  docs/app/templates/components.hbs
  docs/app/templates/modifiers.hbs
  docs/tests/integration/components/sidebar-test.gts
  packages/design-system/src/custom/_scaffold.scss
  packages/design-system/src/main.scss
  packages/design-system/src/utilities/_scrollbar.scss
  packages/ember-core/package.json
  packages/ember-core/src/components/index.ts
  packages/ember-core/src/components/sidebar.gts
  packages/ember-core/src/index.ts
  packages/ember-core/src/template-registry.ts
Labels: enhancement

#388 feat: Create app bar component
  docs/app/controllers/application.ts
  docs/app/templates/application.hbs
  docs/tests/integration/components/app-bar-test.gts
  packages/design-system/src/custom/_scaffold.scss
  packages/ember-core/package.json
  packages/ember-core/src/components/app-bar.gts
  packages/ember-core/src/components/index.ts
  packages/ember-core/src/index.ts
  packages/ember-core/src/template-registry.ts
Labels: enhancement

#390 fix(popover): Use hidden instead of d-none
  docs/tests/integration/components/popover-test.gts
  docs/tests/integration/components/tooltip-test.gts
  packages/ember-core/src/components/popover.gts
Labels: bug

#391 docs(form): Use correct value path
  docs/app/components/f/components/form/index.gts
Labels: documentation

#393 feat: Create context menu component
  docs/app/components/f/components/context-menu.gts
  docs/app/components/f/components/dropdown.gts
  docs/app/router.ts
  docs/app/templates/application.hbs
  docs/app/templates/components/context-menu.hbs
  docs/tests/integration/components/context-menu-test.gts
  packages/design-system/src/custom/_dropdown.scss
  packages/ember-core/package.json
  packages/ember-core/src/components/context-menu.gts
  packages/ember-core/src/components/index.ts
  packages/ember-core/src/index.ts
  packages/ember-core/src/service-registry.ts
  packages/ember-core/src/services/context-menu.ts
Labels: enhancement
