Repository knoxville-utilities-board/nrg-ui, pull requests merged in 2025-05, with the labels that each got.

#458 fix(standards): Use base recommended config for eslint-plugin-n
  packages/ember-core/src/icons.ts
  packages/standards/src/tools/eslint.ts
Labels: bug

#460 style: Move themeswitcher to top of scaffold context menu
  packages/ember-core/src/components/scaffold.gts
Labels: internal

#463 feat: Add invalid and warning color to datetime
  docs/app/components/f/components/form/index.gts
  packages/design-system/src/custom/_forms.scss
Labels: documentation, enhancement

#464 fix(datetime): Show validation messages
  packages/design-system/src/custom/_forms.scss
Labels: bug

#465 chore(ci): Enable testing for Ember 6.4
  .github/workflows/ci.yml
  docs/config/ember-try.js
Labels: internal

#469 refactor(sidebar): Remove click modifier if url or route present
  packages/ember-core/src/components/sidebar.gts
Labels: bug

#471 fix(icon): Use correct type, not component
  packages/ember-core/src/components/icon.gts
  packages/ember-core/src/components/mktg/service-pricing.gts
Labels: bug

#470 feat: Add stacked pane component
  docs/app/router.ts
  docs/app/routes/side-by-side/detail.ts
  docs/app/routes/stacked-pane/selected-item.ts
  docs/app/routes/stacked-pane/selected-item/selected-subitem.ts
  docs/app/routes/stacked-pane/selected-item/selected-subitem/selected-subitem-2.ts
  docs/app/templates/application.hbs
  docs/app/templates/side-by-side.hbs
  docs/app/templates/side-by-side/detail.hbs
  docs/app/templates/side-by-side/index.hbs
  docs/app/templates/stacked-pane.hbs
  docs/app/templates/stacked-pane/index.hbs
  docs/app/templates/stacked-pane/selected-item.hbs
  docs/app/templates/stacked-pane/selected-item/selected-subitem.hbs
  docs/app/templates/stacked-pane/selected-item/selected-subitem/selected-subitem-2.hbs
  packages/design-system/src/custom/_stacked-pane.scss
  packages/design-system/src/main.scss
  packages/ember-core/package.json
  packages/ember-core/src/components/scaffold.gts
  packages/ember-core/src/components/stacked-pane.gts
  packages/ember-core/src/components/stacked-pane/container.ts
  packages/ember-core/src/index.ts
  packages/ember-core/src/template-registry.ts
  packages/ember-core/translations/en-us.json
Labels: enhancement, discussion

#477 fix(blueprint): Use CommonJS version of chalk
  packages/ember-core/package.json
  pnpm-lock.yaml
Labels: bug
