Repository knoxville-utilities-board/nrg-ui, pull requests merged in 2025-04, with the labels that each got.

#399 style: Reduce border on footer to match other scaffold elements
  packages/ember-core/src/components/footer.gts
Labels: internal

#398 fix(app-bar): Add environment yield to mobile drop
  packages/ember-core/src/components/app-bar.gts
Labels: bug

#400 feat: Create scaffold component
  docs/app/assets/css/app.css
  docs/app/assets/images/logo.svg
  docs/app/components/code-block.gts
  docs/app/components/f/components/toaster.gts
  docs/app/controllers/application.ts
  docs/app/router.ts
  docs/app/templates/application.hbs
  docs/app/templates/scaffold.hbs
  docs/ember-cli-build.js
  docs/package.json
  docs/types/global.d.ts
  packages/design-system/src/custom/_scaffold.scss
  packages/design-system/src/custom/_toasts.scss
  packages/ember-core/package.json
  packages/ember-core/src/components/index.ts
  packages/ember-core/src/components/scaffold.gts
  packages/ember-core/src/components/sidebar.gts
  packages/ember-core/src/index.ts
  packages/ember-core/src/template-registry.ts
  pnpm-lock.yaml
Labels: enhancement

#401 feat: Add context menu to scaffold app bar
  docs/app/components/f/components/theme-switcher.gts
  docs/app/components/theme-page.gts
  docs/app/router.ts
  docs/app/templates/application.hbs
  docs/app/templates/components/theme-switcher.hbs
  docs/tests/integration/components/theme-switcher-test.gts
  packages/design-system/src/custom/_scaffold.scss
  packages/ember-core/package.json
  packages/ember-core/src/components/context-menu.gts
  packages/ember-core/src/components/dropdown.gts
  packages/ember-core/src/components/index.ts
  packages/ember-core/src/components/scaffold.gts
  packages/ember-core/src/components/theme-switcher.gts
  packages/ember-core/src/index.ts
  packages/ember-core/src/services/theme.ts
  packages/ember-core/src/template-registry.ts
  packages/ember-core/translations/en-us.json
Labels: enhancement

#403 fix: Correct appbar text colors
  packages/design-system/src/custom/_dropdown.scss
  packages/ember-core/src/components/app-bar.gts
Labels: bug

#402 feat(scaffold): Add basic About modal to context menu
  packages/design-system/src/custom/_modal.scss
  packages/ember-core/src/components/scaffold.gts
  packages/ember-core/translations/en-us.json
Labels: enhancement

#405 feat: Add 'subtle' variant to modals
  docs/app/components/f/components/modal.gts
  packages/design-system/src/custom/_modal.scss
  packages/ember-core/src/components/modal.gts
  packages/ember-core/src/components/scaffold.gts
  packages/ember-core/translations/en-us.json
Labels: enhancement

#406 fix: Correct dark mode colors for date picker
  packages/design-system/src/custom/_forms.scss
  packages/ember-core/src/components/form/-private/calendar.gts
Labels: bug

#409 refactor: Allow all app bar options in each section
  docs/app/templates/application.hbs
  docs/tests/integration/components/app-bar-test.gts
  packages/ember-core/src/components/app-bar.gts
  packages/ember-core/src/components/header.gts
  packages/ember-core/src/components/scaffold.gts
Labels: enhancement

#412 fix: Close sidebar on item clicked
  docs/tests/integration/components/scaffold-test.gts
  docs/types/ember-responsive.d.ts
  packages/ember-core/src/components/scaffold.gts
  packages/ember-core/src/components/sidebar.gts
Labels: bug

#416 feat: Tweak sidebar sizing
  packages/ember-core/src/components/scaffold.gts
Labels: enhancement

#411 feat(search): Refine component behavior to improve user experience
  packages/ember-core/src/components/form/search.gts
Labels: enhancement

#418 fix: Correct breakpoints in responsive service
  packages/ember-core/src/services/responsive.ts
  packages/ember-core/unpublished-development-types/index.d.ts
Labels: bug

#420 feat: Add optional header collapse
  docs/app/components/f/components/header.gts
  packages/ember-core/src/components/app-bar.gts
  packages/ember-core/src/components/header.gts
Labels: enhancement

#423 style: Remove border rounding on sidebar items
  packages/design-system/src/custom/_scaffold.scss
Labels: bug

#422 feat: Create helper to lookup service in a template
  docs/tests/integration/helpers/lookup-service-test.gts
  packages/ember-core/package.json
  packages/ember-core/src/helpers/index.ts
  packages/ember-core/src/helpers/lookup-service.ts
  packages/ember-core/src/index.ts
  packages/ember-core/src/template-registry.ts
Labels: enhancement

#410 chore: Format project
  docs/app/components/f/components/dropdown.gts
  docs/app/components/f/components/footer.gts
  docs/app/components/f/components/navbar.gts
  docs/app/components/f/components/toaster.gts
  docs/app/index.html
  docs/app/router.ts
  docs/app/services/theme.js
  docs/app/templates/application.hbs
  docs/app/templates/cards.hbs
  docs/app/templates/faq.hbs
  docs/app/templates/form.hbs
  docs/app/templates/marketing.hbs
  docs/app/templates/promo.hbs
  docs/app/templates/theme.hbs
  docs/app/templates/workflow-tray.hbs
  docs/tests/index.html
  docs/tests/integration/components/alert-test.gts
  docs/tests/integration/components/popover-test.gts
  docs/tests/integration/components/tooltip-test.gts
  packages/design-system/README.md
  packages/design-system/src/custom/_dropdown.scss
  packages/design-system/src/custom/_popover.scss
  packages/ember-core/.prettierignore
  packages/ember-core/.template-lintrc.cjs
  packages/ember-core/rollup.config.mjs
  packages/ember-core/src/components/button.gts
  packages/ember-core/src/components/form/index.gts
  packages/ember-core/src/components/popover.gts
  packages/ember-core/src/components/tooltip.gts
  packages/ember-core/src/helpers/classes.ts
  packages/ember-core/src/helpers/index.ts
  packages/ember-core/src/index.ts
  packages/ember-core/src/modifiers/index.ts
Labels: internal

#426 feat: Rewrite version computation
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  docs/ember-cli-build.js
  packages/app-version/.gitignore
  packages/app-version/README.md
  packages/app-version/package.json
  packages/app-version/src/index.test.ts
  packages/app-version/src/index.ts
  packages/app-version/tsconfig.json
  packages/app-version/vitest.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: enhancement

#428 feat(scaffold): Use switch for theme picker
  docs/app/components/f/components/dropdown.gts
  packages/design-system/src/custom/_scaffold.scss
  packages/ember-core/src/components/context-menu.gts
  packages/ember-core/src/components/dropdown.gts
  packages/ember-core/src/components/scaffold.gts
  packages/ember-core/translations/en-us.json
Labels: enhancement

#429 fix(blueprint): Add missing dependencies during installation
  docs/ember-cli-build.js
  docs/package.json
  packages/ember-core/blueprints/@nrg-ui-core/index.js
  pnpm-lock.yaml
Labels: bug

#430 fix(version): Provide better error handling
  docs/ember-cli-build.js
  packages/app-version/src/index.test.ts
  packages/app-version/src/index.ts
Labels: bug

#432 fix(standards): Add local Node binaries to PATH
  docs/eslint.config.mjs
  packages/standards/src/utils.ts
Labels: bug

#438 feat: Lookup all tags by date first
  packages/app-version/src/index.test.ts
  packages/app-version/src/index.ts
Labels: enhancement

#439 feat(search): Add yield block if provided
  packages/ember-core/src/components/form/search.gts
Labels: enhancement

#440 feat(popover): Auto update position when open
  packages/ember-core/src/components/popover.gts
Labels: enhancement

#442 fix(marketing header): Add flex collapse attribute to fix mobile styling
  docs/app/components/f/mktg-components/header.gts
  packages/ember-core/src/components/mktg/header.gts
Labels: bug

#445 refactor(ci): Clean up caching and publishing docs
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/plan-release.yml
  .github/workflows/publish-unstable.yml
  .github/workflows/publish.yml
Labels: internal

#446 chore: Format project
  docs/app/components/f/mktg-components/header.gts
  packages/design-system/src/custom/_forms.scss
Labels: internal

#451 chore: Make dark theme mixins more generic
  packages/design-system/src/custom/_buttons.scss
  packages/design-system/src/custom/_shadow.scss
Labels: enhancement
