Repository knoxville-utilities-board/nrg-ui, pull requests merged in 2025-01, with the labels that each got.

#323 feat: Create dropdown component
  apps/docs-app/app/components/f/components/dropdown.gts
  apps/docs-app/app/router.ts
  apps/docs-app/app/templates/components.hbs
  apps/docs-app/app/templates/components/dropdown.hbs
  apps/test-app/tests/integration/components/dropdown-test.gts
  packages/design-system/src/_bootstrap.scss
  packages/design-system/src/custom/_dropdown.scss
  packages/design-system/src/custom/_forms.scss
  packages/design-system/src/main.scss
  packages/ember-core/package.json
  packages/ember-core/src/components/dropdown.gts
  packages/ember-core/src/components/popover.gts
  packages/ember-core/src/index.ts
Labels: enhancement

#327 refactor(select): Rewrite using dropdown
  apps/test-app/tests/integration/components/form/index-test.gts
  apps/test-app/tests/integration/components/form/select-test.gts
  apps/test-app/tests/integration/components/pagination-test.gts
  apps/test-app/tests/unit/utils/string-test.ts
  packages/design-system/src/custom/_forms.scss
  packages/ember-core/package.json
  packages/ember-core/src/components/dropdown.gts
  packages/ember-core/src/components/form/select.gts
  packages/ember-core/src/utils/string.ts
Labels: enhancement, internal

#330 refactor(search): Rewrite using dropdown
  apps/test-app/tests/integration/components/form/search-test.gts
  packages/design-system/src/custom/_dropdown.scss
  packages/design-system/src/custom/_forms.scss
  packages/ember-core/src/components/dropdown.gts
  packages/ember-core/src/components/form/search.gts
  packages/ember-core/src/components/form/select.gts
  packages/ember-core/src/components/popover.gts
Labels: enhancement, internal

#334 chore(ci): Prefer offline dependencies when reasonable
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/plan-release.yml
  .github/workflows/publish-unstable.yml
  .github/workflows/publish.yml
Labels: internal

#336 feat: Create package to fetch application version
  apps/test-app/ember-cli-build.js
  apps/test-app/tests/integration/helpers/version-test.gts
  packages/app-version/.gitignore
  packages/app-version/eslint.config.mjs
  packages/app-version/package.json
  packages/app-version/src/index.ts
  packages/app-version/tsconfig.json
  packages/ember-core/README.md
  packages/ember-core/package.json
  packages/ember-core/src/helpers/index.ts
  packages/ember-core/src/helpers/version.ts
  packages/ember-core/src/index.ts
  packages/ember-core/unpublished-development-types/index.d.ts
  pnpm-lock.yaml
Labels: enhancement

#337 refactor: Use native Ember types and rename docs components
  apps/docs-app/app/components/f/components/button.gts
  apps/docs-app/app/components/f/components/card.gts
  apps/docs-app/app/components/f/components/footer.gts
  apps/docs-app/app/components/f/components/form/checkbox-group.gts
  apps/docs-app/app/components/f/components/form/checkbox.gts
  apps/docs-app/app/components/f/components/form/datetime.gts
  apps/docs-app/app/components/f/components/form/index.gts
  apps/docs-app/app/components/f/components/form/phone-input.gts
  apps/docs-app/app/components/f/components/form/radio-group.gts
  apps/docs-app/app/components/f/components/form/search.gts
  apps/docs-app/app/components/f/components/form/select.gts
  apps/docs-app/app/components/f/components/form/text-area.gts
  apps/docs-app/app/components/f/components/form/text-input.gts
  apps/docs-app/app/components/f/components/header.gts
  apps/docs-app/app/components/f/components/icon.gts
  apps/docs-app/app/components/f/components/modal.gts
  apps/docs-app/app/components/f/components/navbar.gts
  apps/docs-app/app/components/f/components/theme-switcher.gts
  apps/docs-app/app/components/f/components/toaster.gts
  apps/docs-app/app/components/f/mktg-components/card-container.gts
  apps/docs-app/app/components/f/mktg-components/card.gts
  apps/docs-app/app/components/f/mktg-components/faq.gts
  apps/docs-app/app/components/f/mktg-components/footer.gts
  apps/docs-app/app/components/f/mktg-components/header.gts
  apps/docs-app/app/components/f/mktg-components/promo-container.gts
  apps/docs-app/app/components/f/mktg-components/promo.gts
  apps/docs-app/app/components/f/mktg-components/section-header.gts
  apps/docs-app/app/components/f/mktg-components/service-pricing.gts
  apps/docs-app/app/templates/components/form/checkbox-group.hbs
  apps/docs-app/app/templates/components/form/checkbox.hbs
  apps/docs-app/app/templates/components/form/datetime.hbs
  apps/docs-app/app/templates/components/form/index.hbs
  apps/docs-app/app/templates/components/form/phone-input.hbs
  apps/docs-app/app/templates/components/form/radio-group.hbs
  apps/docs-app/app/templates/components/form/search.hbs
  apps/docs-app/app/templates/components/form/select.hbs
  apps/docs-app/app/templates/components/form/text-area.hbs
  apps/docs-app/app/templates/components/form/text-input.hbs
  apps/docs-app/app/templates/mktg-components/card-container.hbs
  apps/docs-app/app/templates/mktg-components/card.hbs
  apps/docs-app/app/templates/mktg-components/faq.hbs
  apps/docs-app/app/templates/mktg-components/footer.hbs
  apps/docs-app/app/templates/mktg-components/header.hbs
  apps/docs-app/app/templates/mktg-components/promo-container.hbs
  apps/docs-app/app/templates/mktg-components/promo.hbs
  apps/docs-app/app/templates/mktg-components/section-header.hbs
  apps/docs-app/app/templates/mktg-components/service-pricing.hbs
  apps/test-app/package.json
  apps/test-app/tests/integration/components/toaster-test.gts
  apps/test-app/tests/unit/services/modal-test.ts
  apps/test-app/types/global.d.ts
  packages/ember-core/package.json
  packages/ember-core/src/components/form/index.gts
  packages/ember-core/src/components/form/select.gts
  packages/ember-core/src/components/index.ts
  packages/ember-core/src/services/toast.ts
  packages/ember-core/src/validation/validators/base.ts
  packages/ember-core/src/validation/validators/custom.ts
  packages/ember-core/unpublished-development-types/index.d.ts
  pnpm-lock.yaml
Labels: internal

#339 fix(app-version): Null-check Embroider macro config
  apps/docs-app/app/templates/index.hbs
  apps/docs-app/ember-cli-build.js
  apps/docs-app/package.json
  packages/ember-core/src/helpers/version.ts
  packages/ember-core/unpublished-development-types/index.d.ts
  pnpm-lock.yaml
Labels: bug

#340 refactor(docs): Convert to native types
  apps/docs-app/package.json
  apps/docs-app/types/global.d.ts
  packages/ember-core/src/services/toast.ts
  pnpm-lock.yaml
Labels: internal

#329 feat: Add flip middleware to popover and tooltip
  apps/docs-app/app/components/f/components/dropdown.gts
  apps/docs-app/app/components/f/components/popover.gts
  apps/docs-app/app/components/f/components/tooltip.gts
  apps/test-app/tests/integration/components/popover-test.gts
  packages/ember-core/src/components/dropdown.gts
  packages/ember-core/src/components/popover.gts
  packages/ember-core/src/components/tooltip.gts
Labels: enhancement

#343 chore(docs): Use correct components
  apps/docs-app/app/templates/components/button.hbs
  apps/docs-app/app/templates/components/card.hbs
  apps/docs-app/app/templates/components/footer.hbs
  apps/docs-app/app/templates/components/header.hbs
  apps/docs-app/app/templates/components/icon.hbs
  apps/docs-app/app/templates/components/modal.hbs
  apps/docs-app/app/templates/components/navbar.hbs
  apps/docs-app/app/templates/components/theme-switcher.hbs
  apps/docs-app/app/templates/components/toaster.hbs
Labels: documentation, internal

#342 fix(search): Properly rehydrate serialized value
  apps/docs-app/app/components/f/components/form/search.gts
  packages/ember-core/src/components/form/search.gts
Labels: bug

#344 chore: Update links in READMEs
  README.md
  packages/design-system/README.md
  packages/ember-core/README.md
  packages/ember-core/src/components/form/index.gts
Labels: documentation

#345 feat: Add optional delay to popover
  apps/docs-app/app/components/f/components/popover.gts
  apps/docs-app/app/components/f/components/tooltip.gts
  packages/ember-core/src/components/popover.gts
  packages/ember-core/src/components/tooltip.gts
Labels: enhancement

#348 refactor: Use d-none instead of hidden for popovers
  apps/test-app/tests/integration/components/popover-test.gts
  apps/test-app/tests/integration/components/tooltip-test.gts
  packages/ember-core/src/components/popover.gts
Labels: enhancement
